# When you're ready to move to spring-cloud-config then this file should be served by that service
# Eureka server has been added and is available as a sibling to the rest module.

spring:
  application.version: @pom.version@

server:
  port: 8080

# When Eureka is available set accordingly
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8071/eureka/
  instance:
    status-page-url: ${management.contextPath}/info
    health-check-url-path: ${management.contextPath}/health

management.contextPath: /admin

# Custom actuators
exception.interceptor.queue.size: 50
exception.interceptor.endpoint: exceptions
exception.interceptor.stacktrace: false
trace.interceptor.queue.size: 50
trace.interceptor.endpoint: requests

# Properties used by /admin/info and /admin/build endpoints.
info.app.name: ${spring.application.name}
info.app.profile: ${spring.profiles.active}
info.app.maven.version: @pom.version@
info.app.maven.artifactId: @pom.artifactId@
info.app.maven.groupId: @pom.groupId@
info.app.ci.build: @ci.build@
info.app.ci.url: @pom.ciManagement.url@

# If you wish to disable hystrix uncomment
#feign.hystrix.enabled: false

# Default feign requests run in different threads
hystrix.command.default.execution.isolation.strategy: SEMAPHORE

# Please remove this setting - added for demo, see AccountClient
account.service.name: ${spring.application.name}

---
spring:
  profiles: development


---
spring:
   profiles: test


---
spring:
   profiles: production






